import test from "node:test";
import assert from "node:assert/strict";
import { readdir, readFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "../../..");
const codaApi = await import("../src/coda/index.js");

const retiredLegacy = /gseos/i;
const retiredShort = /(^|[^A-Za-z0-9])gse(?![A-Za-z0-9])|Gse/;
const isRetiredName = (value) => retiredLegacy.test(value) || retiredShort.test(value);

test("CODA CLI 入口输出与核心 manifest 校验一致", () => {
  const run = spawnSync(process.execPath, [resolve(root, "packages/local-core/src/coda-cli.js"), "manifest"], {
    cwd: root,
    encoding: "utf8",
  });
  assert.equal(run.status, 0, run.stderr);
  const payload = JSON.parse(run.stdout);
  assert.equal(payload.ok, true);
  assert.equal(codaApi.validateCapabilityManifest.length > 0, true);
});

test("CODA 核心模块目录不再保留旧命名转发壳", async () => {
  const entries = await readdir(resolve(root, "packages/local-core/src"));
  assert.ok(entries.includes("coda"), "src/coda 必须存在");
  assert.ok(!entries.includes("gseos"), "src/gseos 兼容转发目录必须已移除");
  assert.ok(!entries.includes("gseos-cli.js"), "gseos-cli.js 兼容入口必须已移除");
});

test("仓库跟踪路径与活动配置中不再出现退役名称", async () => {
  const tracked = spawnSync("git", ["ls-files"], { cwd: root, encoding: "utf8" }).stdout.split("\n");
  assert.deepEqual(tracked.filter((path) => isRetiredName(path)), [], "跟踪路径不得包含退役名称（含 gse 短名）");
  const manifest = JSON.parse(spawnSync(process.execPath, ["-e", `process.stdout.write(require("fs").readFileSync("${root}/contracts/coda/capabilities.json","utf8"))`], { encoding: "utf8" }).stdout);
  assert.equal(manifest.manifest_type, "CODA_CapabilityManifest");
  const legacyMarker = /GENERATED BY \(\?:CODA\|GSEOS\)/;
  const offenders = [];
  for (const file of await readdir(resolve(root, "packages/local-core/src"), { recursive: true })) {
    if (!String(file).endsWith(".js")) continue;
    const lines = (await readFile(resolve(root, "packages/local-core/src", String(file)), "utf8")).split("\n");
    for (const line of lines) if (isRetiredName(line) && !legacyMarker.test(line)) offenders.push(`${file}: ${line.trim()}`);
  }
  assert.deepEqual(offenders, [], "核心源码中除旧生成标记的只读识别外不得再出现退役名称");
});

test("Godot 插件源码中除旧生成标记的只读识别外不得出现退役名称", async () => {
  const allowed = /GENERATED BY GSEOS\./;
  const offenders = [];
  for (const file of await readdir(resolve(root, "addons"), { recursive: true })) {
    if (!/\.[a-z0-9.]+$/i.test(String(file))) continue;
    const lines = (await readFile(resolve(root, "addons", String(file)), "utf8")).split("\n");
    lines.forEach((line, index) => {
      if (isRetiredName(line) && !allowed.test(line)) offenders.push(`addons/${file}:${index + 1}: ${line.trim()}`);
    });
  }
  assert.deepEqual(offenders, [], "插件源码中除旧生成标记的只读识别外不得再出现退役名称");
});

test("旧 GSEOS 生成标记仍按受管工件识别，新生成物使用 CODA 标记", async () => {
  const { verifyManagedArtifact } = await import("../src/coda/index.js");
  const legacy = "# GENERATED BY GSEOS. event=ui.reward.claim plan=sha256:legacy\n# DO NOT EDIT. source is managed outside the runtime.\nextends RefCounted\n";
  assert.equal(verifyManagedArtifact(legacy, { event_id: "ui.reward.claim", plan_fingerprint: "sha256:legacy" }).ok, true);
  const source = await readFile(resolve(root, "packages/local-core/src/coda/codegen.js"), "utf8");
  assert.ok(source.includes("# GENERATED BY CODA."));
});
